### ISSUE TITLE
 new HSSFWorkbook() throw exception.

### ISSUE THREAD

**Issue by luqizheng** [yuleyule66/Npoi.Core#1]
Following code works in NPOI 2.2.4, but NPOI.Core throw exception.

var  workbook = new HSSFWorkbook();
-------------------------------------------------------------------------------------------------------------------
   System.TypeInitializationException : The type initializer for 'Npoi.Core.HSSF.Record.DSFRecord' th
rew an exception.
      ---- System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictio
nary.
      Stack Trace:
           at Npoi.Core.HSSF.Model.InternalWorkbook.CreateWorkbook()
           at Npoi.Core.HSSF.UserModel.HSSFWorkbook..ctor()

**Comment by yuleyule66** [comment]
this is a bug, thanks for your report.

**Comment by yuleyule66** [comment]
Fixed

**Comment by yuleyule66** [comment]
I have already pushed version 1.1.1 to nuget , please upgrade . 

close issue,
