### ISSUE TITLE
读取word异常

### ISSUE THREAD

**Issue by sweetwxh** [yuleyule66/Npoi.Core#14]
用XWPFDocument加载word文档时报错：
System.Xml.XmlException: The ':' character, hexadecimal value 0x3A, cannot be included in a name。
还没试过原始版本的NPOI。

**Comment by yuleyule66** [comment]
NPOI.Core不支持WORD导入。

**Comment by ryanlin1986** [comment]
希望能增加支持， 中国特色， 特别是 政府机关大部分文档还是以doc格式

**Comment by yuleyule66** [comment]
@ryanlin1986  2.0版本已经发布，已经支持word导入导出
http://www.cnblogs.com/savorboard/p/dotnetcore-npoi.html
