### ISSUE TITLE
hot to set font size?

### ISSUE THREAD

**Issue by 591811930** [yuleyule66/Npoi.Core#2]
my code   
            IRow row = sheet1.CreateRow(0);
            row.Height = 30 * 30;
            var cell = row.CreateCell(0);

            //第一行字体
            var font = workbook.CreateFont();
            font.IsBold = true;
            font.FontHeightInPoints = (short)100;
            cell.CellStyle.SetFont(font);

why    font.FontHeightInPoints = (short)100; not work

**Comment by yuleyule66** [comment]
I did a test, it also doesn't work in NPOI

**Comment by 591811930** [comment]
IRow row1 = sheet1.CreateRow(0);
            row1.Height = 30 * 20;
            var cell1 = row1.CreateCell(0);

            var font1 = workbook.CreateFont();
            font1.Boldweight = 18;
            font1.FontHeightInPoints = 18;
            var style1 = workbook.CreateCellStyle();
            style1.VerticalAlignment = VerticalAlignment.Center;
            style1.Alignment = HorizontalAlignment.Center;
            style1.SetFont(font1);

            cell1.SetCellValue("test");
            cell1.CellStyle = style1;

this code works

**Comment by 591811930** [comment]
根据文字 自适应宽度 搞过吗
