### ISSUE TITLE
   IWorkbook book = new HSSFWorkbook();   call this will error

### ISSUE THREAD

**Issue by 591811930** [yuleyule66/Npoi.Core#3]
when I new HSSFWorkbook()   not new XSSFWorkbook()  
this will error  

I don't know why  

以前的项目是可以的

**Comment by yuleyule66** [comment]
see issue #1

**Comment by 591811930** [comment]
how can I fix it?

did you change the version ??
 "Savorboard.NPOI.Core.Ooxml": "1.1.0"

**Comment by yuleyule66** [comment]
I can release 1.1.1 for you. please wait one moment.

**Comment by yuleyule66** [comment]
I have already pushed version 1.1.1 to nuget , please upgrade .

**Comment by yuleyule66** [comment]
this bug fixed in 1.1.3, upgrade nuget package.
