### ISSUE TITLE
利用模板导出之后的Excel文件有问题

### ISSUE THREAD

**Issue by MartinYl** [yuleyule66/Npoi.Core#4]
存在一个Excel模板："模板.xlsx"，打开没有任何问题，但是用NPOI.Core导出成另一个Excel文件之后打开就会报一个问题：
“**发现”XXXXX.xlsx"中的部分内容有问题。是否让我们尽量尝试恢复。如果您信任此工作簿的源，请点击是**“
点击是之后excel可以打开，插入的数据也都在

```
  var newFile = "E:/" + Guid.NewGuid().ToString() + ".xlsx";
  using (var fs = new FileStream(newFile, FileMode.Create, FileAccess.Write))
  {
      //excelPath-模板路径，为传递过来的参数
      IWorkbook wb = new XSSFWorkbook(excelPath);

      ISheet sheet1 = wb.GetSheetAt(0);
      
      //celldata-需要插入的数据，参数          
      foreach (var x in celldata)
      {
          IRow row = sheet1.GetRow(x.Cell);
          row.GetCell(x.Cell).SetCellValue(x.Value);
      }
      wb.Write(fs);
  }
```

**Comment by yuleyule66** [comment]
请问，这个问题在NPOI中是否存在呢？能否帮忙做个测试

**Comment by MartinYl** [comment]
您好，我们之前的项目导出功能就是用的 .NET Framework 4的NPOI写的，也是用的模板导出，读取模板写入数据重新保存到其他地方，是没有问题的
现在的项目用上了.NET Core，之前一直没有Core的NPOI，前段时间找到了您的这个项目，试了一下有这个问题，但是用您的示例代码是没有问题的，也就是说新生成Excel是没有问题的
用模板导出的Excel有问题，但是经过Excel恢复数据，另存为新的，再打开就没事了，是不是文件头有问题呢？

**Comment by QBTomzhu** [comment]
好像 `HSSFWorkbook` 打开文件也会报错

只有 `XSSFWorkbook` 可以打开, 但是生成的excel文件a.xlsx就像 @MartinYl 说的会提示文件损坏之类的

能不能看一下呀 @yuleyule66  
```
      var templateNameWithPath = @"abc.xls";
      HSSFWorkbook workbook;
      using (FileStream file = new FileStream(templateNameWithPath, FileMode.Open, FileAccess.Read))
      {
        workbook = new HSSFWorkbook(file);
      }
```

**Comment by QBTomzhu** [comment]
EFPlus 在dnx里面比NPOI好用多了 @MartinYl

**Comment by luqizheng** [comment]
@QBTomzhu 试一下 FileStream flush一下，看看有没有解决。

**Comment by AllenChen318084** [comment]
請問這個問題是不是還沒解決呢?

**Comment by yuleyule66** [comment]
@AllenChen318084 抱歉这个问题我也解决不了，代码量太多，排查不到。

**Comment by baiyunchen** [comment]
@QBTomzhu EpPlus好像不支持xls格式吧？大家一起完善Npoi.Core才是王道
