### ISSUE TITLE
在ASP.NET Core中，把XSSFWorkbook中的内容写到MemoryStream，然后试图将MemoryStream作为FileStreamResult的参数，返回给到客户端，结果失败 

### ISSUE THREAD

**Issue by NAOnlyOne** [yuleyule66/Npoi.Core#6]
关键代码如下：
using (MemoryStream stream = new MemoryStream())
{
   xssfWorkbook.Write(stream);
   stream.Seek(0, SeekOrigin.Begin);//Error,Cannot access a closed Stream
   return File(stream, "application/ms-excel", DateTime.Now.ToString() + ".xlsx");//Error
}
错误如下：
ObjectDisposedException: Cannot access a closed Stream.
System.IO.MemoryStream.CopyToAsync(Stream destination, int bufferSize, CancellationToken cancellationToken)

这段代码其实是直接从ASP.NET移植过来的，需求是在客户端导出Excel表格。
调试发现在执行Write方法之前，MemoryStream的CanRead、CanWrite等都是true，在Write之后MemoryStream 不能执行任何读写操作，因为它已经是Closed状态，而在ASP.NET中使用NPOI（不是NPOI Core）不会出现这个问题，所以想请教是什么原因导致 MemoryStream 关闭了。

**Comment by yuleyule66** [comment]
Write 之后会关闭Stream，你的这种需求，目前的做法是需要进行一次临时保存和读取。

**Comment by liu7923032** [comment]
临时保存读取太麻烦了,有没有方法解决这种问题呢？
