### ISSUE TITLE
不支持xls格式的文件.

### ISSUE THREAD

**Issue by xiexin36** [yuleyule66/Npoi.Core#7]
无法正确打开xls格式的文件, 直接抛出异常报错.

**Comment by baiyunchen** [comment]
你可以克隆这个仓库到本地，然后把你的代码写到Npoi.Samples.CreateNewSpreadsheet项目中测试，看哪里有BUG，完了提个issue到github或者直接修复掉提Pull Request

**Comment by baiyunchen** [comment]
please reference #11 and retry,i fix some bug.
