### ISSUE TITLE
Fails on creating HSSFWorkbook from template

### ISSUE THREAD

**Issue by DiE-MaRMeLaDe** [yuleyule66/Npoi.Core#8]
My code:
`var templateWorkbook = new HSSFWorkbook(templateStream, true);`

Exception Stack Trace: 
`System.InvalidCastException: Unable to cast object of type 'System.Object[]' to type 'Npoi.Core.HSSF.Record.SharedFormulaRecord[]'.
   at Npoi.Core.HSSF.Model.RowBlocksReader..ctor(RecordStream rs)
   at Npoi.Core.HSSF.Model.InternalSheet..ctor(RecordStream rs)
   at Npoi.Core.HSSF.UserModel.HSSFWorkbook..ctor(DirectoryNode directory, Boolean preserveNodes)
   at Npoi.Core.HSSF.UserModel.HSSFWorkbook..ctor(Stream s, Boolean preserveNodes)`

**Comment by yuleyule66** [comment]
I have found no exception is thrown on my test, the `HSSF` corresponding is 97-2003 (XLS) file, are you using the `.xls`  extensions file?

This is my code:
```
Stream templateStream = new MemoryStream();

using (var file = new FileStream("D:\\TestExcel.xls", FileMode.Open, FileAccess.Read)) {
    file.CopyTo(templateStream);
    templateStream.Seek(0, SeekOrigin.Begin);
}

var templateWorkbook = new HSSFWorkbook(templateStream, true);
```

**Comment by DiE-MaRMeLaDe** [comment]
Thank You. I was reading from file stream directly, like NPOI for .Net Framework
