### ISSUE TITLE
无法导入.xls格式的文件

### ISSUE THREAD

**Issue by csluzhenyu** [yuleyule66/Npoi.Core#9]
System.InvalidCastException:“Unable to cast object of type 'System.Object[]' to type 'Npoi.Core.HSSF.Record.ExternalNameRecord[]'.”

**Comment by yuleyule66** [comment]
please show your code.

**Comment by csluzhenyu** [comment]
public class Program
    {
        public static void Main(string[] args) {
            //ExportExcel();
            //ExportExcelHSSF();
            //ExportWord();
            //ImportExcel();
            ImportExcelHSSF();
            Console.ReadKey();
        }
        private static void ImportExcelHSSF()
        {
            Stream templateStream = new MemoryStream();
            using (var file = new FileStream("D:\\moban.xls", FileMode.Open, FileAccess.Read))
            {
                file.CopyTo(templateStream);
                templateStream.Seek(0, SeekOrigin.Begin);
            }
            var templateWorkbook = new HSSFWorkbook(templateStream, true);
            Console.WriteLine(templateWorkbook.GetSheetAt(0).PhysicalNumberOfRows);
        }
    }

**Comment by csluzhenyu** [comment]
templateWorkbook.GetSheetAt(0) 可以获取到SheetName
但是Row 始终为0
导入.xlsx没有这个问题

**Comment by yuleyule66** [comment]
Ok, Thanks for your report . I will check later.

**Comment by csluzhenyu** [comment]
困扰一天了， 没找到其他的解决方案。

**Comment by EddieDe** [comment]
Hi! Right now I have the same problem with reading an xls-file within HSSFWorkbook. Could you please tell me if you're still going to resolve it? Or maybe you have any ideas on how it can be done? Thanks!

**Comment by baiyunchen** [comment]
please reference #10 ,it's a bug.

**Comment by yuleyule66** [comment]
bug fixed by PR #11.
